name: '.NET core version detector'
description: 'Determines the version of .NET core to install based on the contents of global.json'
branding:
  icon: 'git-merge'
  color: 'gray-dark'
inputs:
 file:
    desciption: 'path to global.json'
    default: src/global.json
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/detect ${{ inputs.file }}
      shell: bash
